function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    BETTA=1/(1+params(2)/400);
    A=params(5);
    ys_(8)=A;
    Q=params(4);
    ys_(7)=Q;
    UPSILON=1;
    UK=params(10);
    ys_(9)=UK;
    PSSIK=0;
    RK=Q*(1/BETTA+params(3)-1)/UK+PSSIK/UK;
    ys_(4)=RK;
    KS_o_L=(A*params(1)/RK)^(1/(1-params(1)));
    K_o_L=KS_o_L/UK;
    Y_o_L=A*KS_o_L^params(1);
    YS_o_L=Y_o_L-PSSIK*K_o_L;
    IV_o_L=params(3)*K_o_L/UPSILON;
    SAV=IV_o_L/YS_o_L;
    C_o_L=YS_o_L*(1-SAV);
    YD_o_L=((1-SAV)*(C_o_L/(1-SAV))^(1+params(8))+SAV*(IV_o_L/SAV)^(1+params(8)))^(1/(1+params(8)));
    XC=(C_o_L/((1-SAV)*YD_o_L))^params(8);
    XIV=(IV_o_L/(SAV*YD_o_L))^params(8);
    HAB_o_L=0;
    DHABP_DC=0;
    L=1;
    DU_DC=(C_o_L*L-HAB_o_L*L)^(-1);
    DUP_DC=(C_o_L*L-HAB_o_L*L)^(-1)*(-DHABP_DC);
    LAM=XC^(-1)*(DU_DC+BETTA*DUP_DC);
    ys_(1)=Y_o_L*L;
    ys_(2)=C_o_L*L;
    ys_(5)=K_o_L*L;
    ys_(3)=IV_o_L*L;
    ys_(6)=LAM;
    % Auxiliary equations
    check_=0;
end
